### ISSUE TITLE
Main Styles format

### ISSUE THREAD

**Issue by ManJurkus** [front-end-by-rimantas/44-grupe-portfolio-seo-crawler#6]

**Comment by ZygimantasL** [comment]
Sustilizuoti h1 elementą. pagrindinis hero tekstas 
Sustilizuoti h2 elementą. Sekcijų Pirmas sakinys
sustilizuoti h3 elementą . Sekcijų pavadinimai mažų šriftu. su spalvomis teksto savybem ir t.t.
sustilizuot paragrafus
